---
name: Sample
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: email123
enabled: false
trigger:
  type: email123.imap.message
  parameters: {}
criteria:
  trigger.from:
    pattern: harsh6100@gmail.com
    type: contains
action:
  ref: core.local
  parameters:
    cmd: echo hello world
